sudo: false

language: node_js

node_js:
  - '6'
  - '8'
  - '9'
  - '10'

services:
  - docker

before_install:
  - docker pull opendxl/opendxl-broker
  - docker run -d -p 127.0.0.1:8883:8883 -p 127.0.0.1:8443:8443 -p 127.0.0.1:443:443 opendxl/opendxl-broker
  - docker ps -a

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_script:
  - bin/dxlclient.js provisionconfig -u admin -p password test/integration 127.0.0.1 client
  - cp test/integration/dxlclient.config test/integration/client_config.cfg
  - cat test/integration/client_config.cfg

script:
  - echo Running tests with MQTT
  - npm run ci
  - sed -i -e "s/#UseWebSockets=false/UseWebSockets=true/g" test/integration/client_config.cfg
  - cat test/integration/client_config.cfg
  - echo Running tests with WebSockets
  - npm run test

